### ISSUE TITLE
HELP ITZ A MEEEEESSSSSSSSSSS :(

### ISSUE THREAD

**Issue by eliaslfox** [eliaslfox/MissionBit-Fall-2015#15]

**Comment by choochootrain** [comment]
This is actually organized pretty nicely. Theres a couple little things which will help you out and keep things consistent. Once you add Angular and a full frontend, the javascript issues will be solved so I won't comment on those.
- Consolidate vendor dependencies: Add bootstrap, jquery with bower so you can serve a local copy of it instead of linking to a remote version
- use https://github.com/web-napopa/node-reversable-router: when creating a route, you can give it a name. use that name in your jade templates instead of hardcoding the route
- Consider using scss or less: youre using jade which is pretty nice, so if you want to use something similar for css, check out scss
- remove apidoc from git: General rule of thumb is that any file which can be autogenerated from other files should not be version controlled.
